eno=int(input("Enter employee number"))
ename=input("Enter Employee Name:")
esal=float(input("Enter Employee Salary:"))
eaddr=input("Enter Employee Address:")
married=bool(input("Employee Married ?[True|False]:"))
print(eno)
print(ename)
print(esal)
print(eaddr)
print(married)